name: hammerspace
favicon: null
layout_spectrum: 0.4306771655101329
typography_spectrum: 0.026454200502485037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7641696203500032
  lightness: 0.8256626948714256
  saturation: 0.5761436128523201
  rhythmicContrast: 0.28244496672414243
purpose: []
