name: hammerspace
favicon: null
layout_spectrum: 0.37805
typography_spectrum: 0.48874
title: hammerspace
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#20587e'
    - '#ffffff'
    - '#c4c4c4'
    - '#102c41'
  brandStrength: 0.7641696203500032
  lightness: 0.8256626948714256
  saturation: 0.5761436128523201
  rhythmicContrast: 0.28244496672414243
purpose: []
