name: hammerspace
favicon: null
layout_spectrum: 0.50375
typography_spectrum: 0.25047
title: hammerspace
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#20587e'
    - '#ffffff'
    - '#c4c4c4'
    - '#102c41'
  brandStrength: 1
  lightness: 0.8256626948714256
  saturation: 0.1875
  rhythmicContrast: 0.28244496672414243
purpose: []
